apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: loneworker-cpu-autoscale 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: loneworker
  minReplicas: 1 
  maxReplicas: 8
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 30
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 100
      policies:
      - type: Pods
        value: 2
        periodSeconds: 120
      - type: Percent
        value: 50
        periodSeconds: 20
      selectPolicy: Max   
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 2
        periodSeconds: 20      
      - type: Percent
        value: 10
        periodSeconds: 10
      selectPolicy: Min
